### ISSUE TITLE
this._callbacks

### ISSUE THREAD

**Issue by lneir** [bredele/emitter-queue#1]
Thanks for code, but not sure how current code works...

this._callbacks is never assigned anything.

believe in emitter.on method need to add something like:
```
if (!this._callbacks) {
    this._callbacks = {};
}
this._callbacks[topic] = true;
```

**Comment by bredele** [comment]
thanks @lneir I will take a look at that tonight.

**Comment by bredele** [comment]
@lneir I wanted to make sure it works [component-emitter](https://github.com/component/emitter/blob/master/index.js).
